server.port=8081
spring.application.name=tgdd
spring.data.mongodb.uri=mongodb://localhost:27017/tgdd_clone
spring.thymeleaf.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework=INFO
logging.level.com.example.tgdd=DEBUG
